create table hotel.accounts(
	account_id serial primary key, -- auto-generated by database
	
	user_name text, -- username used to log in
	pass_word text, -- password used to log in
	
	full_name text, -- name of the user
	full_address text, -- address of the user
	
	email text, -- email of the user
	phone_number text -- phone number of the user
);

insert into hotel.accounts (user_name, pass_word, full_name, full_address, email, phone_number) 
	values ('username', 'password', 'full name', 'full address', 'email', 'phone number');

insert into hotel.accounts (user_name, pass_word, full_name, full_address, email, phone_number) 
	values ('username2', 'password', 'full name', 'full address', 'email', 'phone number');

insert into hotel.accounts (user_name, pass_word, full_name, full_address, email, phone_number) 
	values ('username3', 'password', 'full name', 'full address', 'email', 'phone number');

create table hotel.rooms(
	room_type text primary key, -- type of hotel room
	room_price int -- price per night in this type of hotel room
);

insert into hotel.rooms (room_type, room_price) values ('single', 200);
insert into hotel.rooms (room_type, room_price) values ('double', 300);
insert into hotel.rooms (room_type, room_price) values ('suite', 400);

-- Date Format
-- 1999-01-08
-- year-month-day
	
-- Time Format
-- hour:minute AM/PM

create table hotel.dates(
	
	reservation_date date primary key, -- date the reservation will be made
	check_in_time time, -- time after which the user can check into the hotel if their reservation starts on this day
	check_out_time time -- time by which the user needs to check out of the hotel if their last stay is on this day
	
);

-- Date Format
-- 1999-01-08
-- year-month-day

-- Time Format
-- hour:minute AM/PM

insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-19', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-20', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-21', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-22', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-23', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-24', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-25', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-26', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-27', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-28', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-29', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-4-30', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-01', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-02', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-03', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-04', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-05', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-06', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-07', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-08', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-09', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-10', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-11', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-12', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-13', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-14', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-15', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-16', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-17', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-18', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-19', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-20', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-21', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-22', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-23', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-24', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-25', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-26', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-27', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-28', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-29', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-30', '03:00 PM', '11:00 AM');
insert into hotel.dates (reservation_date, check_in_time, check_out_time) values ('2021-5-31', '03:00 PM', '11:00 AM');

-- Date Format
-- 1999-01-08
-- year-month-day

-- Time Format
-- hour:minute AM/PM

create table hotel.reservations(

	reservation_id serial primary key, -- auto-generated by database
	account_id int, -- account id of the person who booked the room
	
	reservation_start_date date, -- date they check into the hotel
	reservation_end_date date, -- day they check out of hotel
	
	check_in_time time, -- time after which the user can check into the hotel if their reservation starts on this day
	check_out_time time, -- time by which the user needs to check out of the hotel if their last stay is on this day
	
	room_type text, -- type of hotel room
	room_price int, -- price per night in this type of hotel room
	
	number_of_nights int, -- number of nights the user will be staying at the hotel
	reservation_price int -- price of the hotel stay based on the type of room booked and the number of nights booked
	
);

-- Date Format
-- 1999-01-08
-- year-month-day

-- Time Format
-- hour:minute AM/PM

insert into hotel.reservations (account_id, reservation_start_date, reservation_end_date, check_in_time, check_out_time,
	room_type, room_price, number_of_nights, reservation_price) 
	values (1, '2021-05-01', '2021-05-10', '3:00 PM', '11:00 AM', 'single', 200, 9, 1800);

insert into hotel.reservations (account_id, reservation_start_date, reservation_end_date, check_in_time, check_out_time,
	room_type, room_price, number_of_nights, reservation_price) 
	values (1, '2021-05-13', '2021-05-14', '3:00 PM', '11:00 AM', 'suite', 400, 1, 400);

insert into hotel.reservations (account_id, reservation_start_date, reservation_end_date, check_in_time, check_out_time,
	room_type, room_price, number_of_nights, reservation_price) 
	values (1, '2021-05-20', '2021-05-23', '3:00 PM', '11:00 AM', 'single', 200, 3, 600);

insert into hotel.reservations (account_id, reservation_start_date, reservation_end_date, check_in_time, check_out_time,
	room_type, room_price, number_of_nights, reservation_price) 
	values (2, '2021-05-01', '2021-05-10', '3:00 PM', '11:00 AM', 'double', 300, 9, 2700);

insert into hotel.reservations (account_id, reservation_start_date, reservation_end_date, check_in_time, check_out_time,
	room_type, room_price, number_of_nights, reservation_price) 
	values (3, '2021-05-01', '2021-05-03', '3:00 PM', '11:00 AM', 'single', 300, 2, 600);


select * from hotel.accounts;
select * from hotel.reservations;
select * from hotel.rooms;
select * from hotel.dates;

