package com.hotel.pojo;

import java.sql.Date;
import java.sql.Time;

public class Reservation {
	
	private int reservationId; // automatically generated by the database to uniquely identify this reservation

	private int accountId;  // id of the account making the reservation
	
	private Date reservationStartDate; // user checks into hotel on this day
	
	private Date reservationEndDate; // user checks out of hotel on this day
	
	private Time checkInTime; // user can check in after this time
	
	private Time checkOutTime; // user must check out by this time
	
	private String roomType; // type of room the user wants to book
	
	private int roomPrice; // price of one night's stay in a particular type of room
	
	private int numberOfNights; // number of nights the user reserved at the hotel
	
	private int reservationPrice; // based on the type and number of rooms booked
	
	public int getReservationId() {
		return reservationId;
	}

	public void setReservationId(int reservationId) {
		this.reservationId = reservationId;
	}

	public int getAccountId() {
		return accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public Date getReservationStartDate() {
		return reservationStartDate;
	}

	public void setReservationStartDate(Date reservationStartDate) {
		this.reservationStartDate = reservationStartDate;
	}

	public Date getReservationEndDate() {
		return reservationEndDate;
	}

	public void setReservationEndDate(Date reservationEndDate) {
		this.reservationEndDate = reservationEndDate;
	}
	
	public Time getCheckInTime() {
		return checkInTime;
	}

	public void setCheckInTime(Time checkInTime) {
		this.checkInTime = checkInTime;
	}

	public Time getCheckOutTime() {
		return checkOutTime;
	}

	public void setCheckOutTime(Time checkOutTime) {
		this.checkOutTime = checkOutTime;
	}
	
	public String getRoomType() {
		return roomType;
	}

	public void setRoomType(String roomType) {
		this.roomType = roomType;
	}

	public int getRoomPrice() {
		return roomPrice;
	}

	public void setRoomPrice(int roomPrice) {
		this.roomPrice = roomPrice;
	}
	
	public int getNumberOfNights() {
		return numberOfNights;
	}

	public void setNumberOfNights(int numberOfNights) {
		this.numberOfNights = numberOfNights;
	}

	public int getReservationPrice() {
		return reservationPrice;
	}

	public void setReservationPrice(int reservationPrice) {
		this.reservationPrice = reservationPrice;
	}

	public Reservation() {
		super();
	}
	
	public Reservation(int accountId, String roomType, Date reservationStartDate, Time checkInTime,
			Date reservationEndDate, Time checkOutTime, int reservationPrice) {
		super();
		this.accountId = accountId;
		this.roomType = roomType;
		this.reservationStartDate = reservationStartDate;
		this.checkInTime = checkInTime;
		this.reservationEndDate = reservationEndDate;
		this.checkOutTime = checkOutTime;
		this.reservationPrice = reservationPrice;
	}
	
	public Reservation(int reservationId, int accountId, String roomType, Date reservationStartDate, Time checkInTime,
			Date reservationEndDate, Time checkOutTime, int reservationPrice) {
		super();
		this.reservationId = reservationId;
		this.accountId = accountId;
		this.roomType = roomType;
		this.reservationStartDate = reservationStartDate;
		this.checkInTime = checkInTime;
		this.reservationEndDate = reservationEndDate;
		this.checkOutTime = checkOutTime;
		this.reservationPrice = reservationPrice;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + accountId;
		result = prime * result + ((checkInTime == null) ? 0 : checkInTime.hashCode());
		result = prime * result + ((checkOutTime == null) ? 0 : checkOutTime.hashCode());
		result = prime * result + numberOfNights;
		result = prime * result + ((reservationEndDate == null) ? 0 : reservationEndDate.hashCode());
		result = prime * result + reservationId;
		result = prime * result + reservationPrice;
		result = prime * result + ((reservationStartDate == null) ? 0 : reservationStartDate.hashCode());
		result = prime * result + roomPrice;
		result = prime * result + ((roomType == null) ? 0 : roomType.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Reservation other = (Reservation) obj;
		if (accountId != other.accountId)
			return false;
		if (checkInTime == null) {
			if (other.checkInTime != null)
				return false;
		} else if (!checkInTime.equals(other.checkInTime))
			return false;
		if (checkOutTime == null) {
			if (other.checkOutTime != null)
				return false;
		} else if (!checkOutTime.equals(other.checkOutTime))
			return false;
		if (numberOfNights != other.numberOfNights)
			return false;
		if (reservationEndDate == null) {
			if (other.reservationEndDate != null)
				return false;
		} else if (!reservationEndDate.equals(other.reservationEndDate))
			return false;
		if (reservationId != other.reservationId)
			return false;
		if (reservationPrice != other.reservationPrice)
			return false;
		if (reservationStartDate == null) {
			if (other.reservationStartDate != null)
				return false;
		} else if (!reservationStartDate.equals(other.reservationStartDate))
			return false;
		if (roomPrice != other.roomPrice)
			return false;
		if (roomType == null) {
			if (other.roomType != null)
				return false;
		} else if (!roomType.equals(other.roomType))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Reservation [reservationId=" + reservationId + ", accountId=" + accountId + ", reservationStartDate="
				+ reservationStartDate + ", reservationEndDate=" + reservationEndDate + ", checkInTime=" + checkInTime
				+ ", checkOutTime=" + checkOutTime + ", roomType=" + roomType + ", roomPrice=" + roomPrice
				+ ", numberOfNights=" + numberOfNights + ", reservationPrice=" + reservationPrice + "]";
	}
	
}
