package com.hotel.pojo;

import java.sql.Date;
import java.sql.Time;

public class Reservation {
	
	private int reservationId; // automatically generated by the database to uniquely identify this reservation

	private int accountId;  // id of the account making the reservation
	
	private String roomType; // type of room the user wants to book
	
	private Date reservationStartDate; // user checks into hotel on this day
	
	private Time checkInTime; // user can check in after this time
	
	private Date reservationEndDate; // user checks out of hotel on this day
	
	private Time checkOutTime; // user must check out by this time
	
	private int reservationPrice; // based on the type and number of rooms booked
	
}
